source/repos/LeandroSous4/MobWeb/MobWeb/MobWeb/Models/Usuario.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MobWeb.Models
{
    public class Usuario
    {
        public int UsuarioId { get; set; }
        [StringLength(45)]
        [Required(ErrorMessage = "Digite seu Nome")]
        public string Nome { get; set; }
        [StringLength(45)]
        [Required(ErrorMessage = "Digite seu Apelido")]
        public string Apelido { get; set; }
        [StringLength(45)]
        [Required(ErrorMessage = "Digite seu E-mail")]
        public string Email { get; set; }
        [StringLength(16)]
        [Required(ErrorMessage = "Digite sua Senha")]
        public string Senha { get; set; }
        [StringLength(11)]
        [Required(ErrorMessage = "Digite seu Telefone")]
        public string Telefone { get; set; }
        public List<Cliente> Clientes { get; set; }
        IHttpContextAccessor HttpContextAccessor { get; set; }

        public Usuario() { }

        public Usuario(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }
    }
}

source/repos/LeandroSous4/MobWeb/MobWeb/MobWeb/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MobWeb.Repositories;
using Microsoft.AspNetCore.Http;
using MobWeb.Models;

namespace MobWeb.Controllers
{
    public class UsuarioController : Controller
    {
        IHttpContextAccessor HttpContextAccessor;
        private readonly IUsuarioRepository _usuarioRepository;
        private readonly IClienteRepository _clienteRepository;

        public UsuarioController(IHttpContextAccessor httpContextAccessor, IUsuarioRepository usuarioRepository, IClienteRepository clienteRepository)
        {
            HttpContextAccessor = httpContextAccessor;
            _usuarioRepository = usuarioRepository;
            _clienteRepository = clienteRepository;
        }


        [HttpGet]
        public IActionResult Login(int? id)
        {
            if (id != null)
            {
                if (id == 0)
                {
                    HttpContext.Session.SetString("NomeUsuarioLogado", string.Empty);
                    HttpContext.Session.SetString("IdUsuarioLogado", string.Empty);
                }
            }
            return View();
        }
        [HttpPost]
        public IActionResult ValidarLogin(Usuario usuario)
        {
            Usuario Login = _usuarioRepository.GetUsuario(usuario);
            if (Login != null)
            {
                HttpContext.Session.SetString("NomeUsuarioLogado", Login.Nome);
                HttpContext.Session.SetString("IdUsuarioLogado", Login.UsuarioId.ToString());
                return RedirectToAction("List", "Cliente");
            }
            else
            {
                TempData["LoginInvalido"] = "Dados de login inválidos!";
                return RedirectToAction("Login");
            }
        }

        [HttpPost]
        public IActionResult Registrar(Usuario usuario)
        {
            if(usuario.UsuarioId == 0)
            {
                if (ModelState.IsValid)
                {
                    _usuarioRepository.Salvar(usuario);
                    return RedirectToAction("Sucesso");
                }
            }
            else
            {
                _usuarioRepository.Atualizar(usuario);
                return RedirectToAction("MeusDados");

            }
            return View();
        }
        [HttpGet]
        public IActionResult Registrar()
        {
            return View();
        }
        public IActionResult MeusDados()
        {
            try
            {
                var idUsuario = int.Parse(HttpContextAccessor.HttpContext.Session.GetString("IdUsuarioLogado"));
                ViewBag.Usuario = _usuarioRepository.DadosUsuario(idUsuario);
                return View();
            }
            catch
            {
                return RedirectToAction("List", "Cliente");
            }
        }

        public IActionResult Sucesso()
        {
            return View();
        }
        [HttpGet]
        [HttpPost]
        public IActionResult DeletarConta()
        {
            var idUsuario = int.Parse(HttpContextAccessor.HttpContext.Session.GetString("IdUsuarioLogado"));
            Usuario usuario = _usuarioRepository.DadosUsuario(idUsuario);
            _usuarioRepository.Deletar(usuario);
            return RedirectToAction("Login");
        }
    }
}

source/repos/LeandroSous4/MobWeb/MobWeb/MobWeb/Views/Usuario/Login.cshtml
@model Usuario

@{
    Layout = "../shared/_LayoutLogin.cshtml";
}

<div class="container" style="background-color:rgba(239, 239, 239, 0.95); border-radius: 10px; padding: 20px; width: 300px;">
    @{
        try
        {
            if (TempData["LoginInvalido"] != null)
            {
                <div class="alert alert-danger">
                    <strong>ATENÇÃO!</strong> @TempData["LoginInvalido"]
                </div>
            }
        }
        catch { }
    }
    <form asp-controller="Usuario" asp-action="ValidarLogin">
        <div class="form-group">
            <label for="email">Email:</label>
            <input id="login" type="email" asp-for="Email">
        </div>
        <div class="form-group">
            <label for="pwd">Senha:</label>
            <input id="senha" type="password" asp-for="Senha">
        </div>
        <button type="submit" class="btn btn-default">Entrar</button>
        <button type="button" class="btn btn-primary" onclick="javascript: window.location.href='../../Usuario/Registrar'">Registrar</button>
    </form>
</div>
<script>
    $('#login').puiinputtext();
    $('#senha').puiinputtext();
</script>

source/repos/LeandroSous4/MobWeb/MobWeb/MobWeb/Views/Usuario/MeusDados.cshtml
@model Usuario

@{
    var UsuarioId = 0;
    var Nome = "";
    var Apelido = "";
    var Email = "";
    var Senha = "";
    var Telefone = "";
    try
    {
        UsuarioId = int.Parse(ViewBag.Usuario.UsuarioId.ToString());
        Nome = ViewBag.Usuario.Nome.ToString();
        Apelido = ViewBag.Usuario.Apelido.ToString();
        Email = ViewBag.Usuario.Email.ToString();
        Senha = ViewBag.Usuario.Senha.ToString();
        Telefone = ViewBag.Usuario.Telefone.ToString();
    }
    catch { }
}


<div class="container-fluid form-group card" style="width: 600px;">
    <h2 class="text-center">Meus Dados</h2>

    <form asp-controller="Usuario" asp-action="Registrar">
        <input type="hidden" asp-for="UsuarioId" value="@UsuarioId" />

        <div class="form-group">
            <label>Nome:</label>
            <input type="text" asp-for="Nome" value="@Nome" />
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Apelido:</label>
            <input type="text" asp-for="Apelido" value="@Apelido" />
            <span asp-validation-for="Apelido" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Email:</label>
            <input type="text" asp-for="Email" value="@Email" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Senha:</label>
            <input type="password" asp-for="Senha" value="@Senha" />
            <span asp-validation-for="Senha" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Telefone:</label>
            <input type="text" asp-for="Telefone" value="@Telefone" />
            <span asp-validation-for="Telefone" class="text-danger"></span>
        </div>
        <button type="submit" class="center-block">Salvar Alterações</button>
        <br /><br /><br />
        <button type="button" class="center-block" onclick="Deletar()">Excluir Minha Conta</button>
    </form>
</div>
<script>
    $('input').puiinputtext();
    $('button').puibutton();
    function Deletar() {
        window.location.href = '../Usuario/DeletarConta';
    }
</script>

source/repos/LeandroSous4/MobWeb/MobWeb/MobWeb/Views/Usuario/Registrar.cshtml
@model Usuario

@{
    Layout = "../shared/_LayoutLogin.cshtml";
}

<div class="container" style="background-color:rgba(239, 239, 239, 0.95); border-radius: 10px; padding: 20px; width: 500px;">
    <h3>Registar-me</h3>
    <br />
    <form asp-controller="Usuario" asp-action="Registrar">
        <div class="form-group">
            <label for="email">Nome:</label>
            <input type="text" class="form-control" asp-for="Nome">
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="apelido">Apelido:</label>
            <input type="text" class="form-control" asp-for="Apelido">
            <span asp-validation-for="Apelido" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" asp-for="Email">
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="pwd">Senha:</label>
            <input type="password" class="form-control" asp-for="Senha">
            <span asp-validation-for="Senha" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="tel">Telefone:</label>
            <input type="tel" class="form-control" asp-for="Telefone">
            <span asp-validation-for="Telefone" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-block btn-success">Registrar-se</button>
    </form>
</div>
<script>
    $('input').puiinputtext();
    $('button').puibutton();
</script>

source/repos/LeandroSous4/MobWeb/MobWeb/MobWeb/Views/Usuario/Sucesso.cshtml
@{
    Layout = "../shared/_LayoutLogin.cshtml";
}

<div class="container" style="background-color:rgba(239, 239, 239, 0.95); border-radius: 10px; padding: 20px;">
    <h1>Cadastro realizado com sucesso!</h1>
    <h4><a href="..\Usuario\Login">Clique aqui</a> para efetuar login.</h4>
</div>