source/repos/LeandroSous4/MobWeb/MobWeb/MobWeb/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MobWeb.Models
{
    public class Cliente
    {
        public int ClienteId { get; set; }
        [StringLength(100)]
        [Required(ErrorMessage = "Digite sua Razão Social")]
        public string RazaoSocial { get; set; }
        [StringLength(14)]
        [Required(ErrorMessage = "Digite seu CNPJ")]
        public string CNPJ { get; set; }
        [StringLength(100)]
        [Required(ErrorMessage = "Digite seu Logradouro")]
        public string Logradouro { get; set; }
        [Required]
        public int Numero { get; set; }
        [StringLength(45)]
        [Required(ErrorMessage = "Digite seu Bairro")]
        public string Bairro { get; set; }
        [StringLength(45)]
        [Required(ErrorMessage = "Digite seu Complemento")]
        public string Complemento { get; set; }
        [StringLength(8)]
        [Required(ErrorMessage = "Digite seu CEP")]
        public string CEP { get; set; }
        public int UsuarioId { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}

source/repos/LeandroSous4/MobWeb/MobWeb/MobWeb/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MobWeb.Repositories;
using MobWeb.Models;
using Microsoft.AspNetCore.Http;

namespace MobWeb.Controllers
{
    public class ClienteController : Controller
    {
        IHttpContextAccessor HttpContextAccessor;
        private readonly IUsuarioRepository _usuarioRepository;
        private readonly IClienteRepository _clienteRepository;

        public ClienteController(IHttpContextAccessor httpContextAccessor, IUsuarioRepository usuarioRepository, IClienteRepository clienteRepository)
        {
            HttpContextAccessor = httpContextAccessor;
            _usuarioRepository = usuarioRepository;
            _clienteRepository = clienteRepository;
        }
        
        public IActionResult List()
        {
            try
            {
                var idUsuario = int.Parse(HttpContextAccessor.HttpContext.Session.GetString("IdUsuarioLogado"));
                ViewBag.ListaClientes = _clienteRepository.ListaClientes(idUsuario);
                return View();
            }
            catch
            {
                return RedirectToAction("Login", "Usuario");
            }
        }
        [HttpPost]
        public IActionResult CadastrarCliente(Cliente cliente)
        {
            if(cliente.ClienteId == 0)
            {
                if (ModelState.IsValid)
                {
                    cliente.UsuarioId = int.Parse(HttpContextAccessor.HttpContext.Session.GetString("IdUsuarioLogado"));
                    _clienteRepository.Salvar(cliente);
                }
                else
                {
                    return View();
                }
                return RedirectToAction("List");
                
            }
            else
            {
                _clienteRepository.Atualizar(cliente);
                return RedirectToAction("List");
            }
        }
        [HttpGet]
        public IActionResult CadastrarCliente(int? id)
        {
            if (id != 0)
            {
                ViewBag.Cliente = _clienteRepository.GetClienteById(id);
            }
            return View();
        }

        [HttpPost]
        [HttpGet]
        public IActionResult DeletarCliente(int id)
        {
            Cliente cliente = _clienteRepository.GetClienteById(id);
            _clienteRepository.Deletar(cliente);
            return RedirectToAction("List");
        }
    }
}

source/repos/LeandroSous4/MobWeb/MobWeb/MobWeb/Views/Cliente/CadastrarCliente.cshtml
@model Cliente

@{
    var clienteId = 0;
    var RazaoSocial = "";
    var CNPJ = "";
    var Logradouro = "";
    var Numero = 0;
    var Bairro = "";
    var Complemento = "";
    var CEP = "";
    var UsuarioId = 0;
    try
    {
        clienteId = int.Parse(ViewBag.Cliente.ClienteId.ToString());
        RazaoSocial = ViewBag.Cliente.RazaoSocial.ToString();
        CNPJ = ViewBag.Cliente.CNPJ.ToString();
        Logradouro = ViewBag.Cliente.Logradouro.ToString();
        Numero = int.Parse(ViewBag.Cliente.Numero.ToString()); ;
        Bairro = ViewBag.Cliente.Bairro.ToString();
        Complemento = ViewBag.Cliente.Complemento.ToString();
        CEP = ViewBag.Cliente.CEP.ToString();
        UsuarioId = int.Parse(ViewBag.Cliente.UsuarioId.ToString());
    }
    catch { }
}


<div class="container-fluid form-group card" style="width: 600px;">
    <h2 class="text-center">Cadastrar Cliente</h2>
    
    <form asp-controller="Cliente" asp-action="CadastrarCliente">
        <input type="hidden" asp-for="ClienteId" value="@clienteId" />

        <div class="form-group">
            <label>Razão Social:</label>
            <input type="text" asp-for="RazaoSocial" value="@RazaoSocial" />
            <span asp-validation-for="RazaoSocial" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>CNPJ:</label>
            <input type="text" asp-for="CNPJ" value="@CNPJ" />
            <span asp-validation-for="CNPJ" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Logradouro:</label>
            <input type="text" asp-for="Logradouro" value="@Logradouro" />
            <span asp-validation-for="Logradouro" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Numero:</label>
            <input type="number" asp-for="Numero" value="@Numero" />
            <span asp-validation-for="Numero" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Bairro:</label>
            <input type="text" asp-for="Bairro" value="@Bairro" />
            <span asp-validation-for="Bairro" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Complemento:</label>
            <input type="text" asp-for="Complemento" value="@Complemento" />
            <span asp-validation-for="Complemento" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>CEP:</label>
            <input type="text" asp-for="CEP" value="@CEP" />
            <span asp-validation-for="CEP" class="text-danger"></span>
        </div>
        <button type="submit" class="center-block">Registrar Cliente</button>
    </form>
</div>
<script>
    $('input').puiinputtext();
    $('button').puibutton();
</script>

source/repos/LeandroSous4/MobWeb/MobWeb/MobWeb/Views/Cliente/List.cshtml
@model IEnumerable<MobWeb.Models.Cliente>

@{
    ViewData["Title"] = "List";
}

<div class="center-block container-fluid">
    <h2>Clientes</h2>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Razao Social</th>
                <th>CNPJ</th>
                <th>Logradoro</th>
                <th>Numero</th>
                <th>Bairro</th>
                <th>Complemento</th>
                <th>CEP</th>
                <th>ID do Usuario</th>
                <th>Excluir</th>
                <th>Editar</th>
            </tr>
        </thead>

        @{
            foreach (var item in (IEnumerable<Cliente>)ViewBag.ListaClientes)
            {
                <tbody>
                    <tr>
                        <td>@item.ClienteId.ToString()</td>
                        <td>@item.RazaoSocial.ToString()</td>
                        <td>@item.CNPJ.ToString()</td>
                        <td>@item.Logradouro.ToString()</td>
                        <td>@item.Numero.ToString()</td>
                        <td>@item.Bairro.ToString()</td>
                        <td>@item.Complemento.ToString()</td>
                        <td>@item.CEP.ToString()</td>
                        <td>@item.UsuarioId.ToString()</td>
                        <td><button type="button" class="btn btn-danger" onclick="Deletar(@item.ClienteId.ToString())">Excluir</button></td>
                        <td><button type="button" class="btn btn-primary" onclick="Editar(@item.ClienteId.ToString())">Editar</button></td>
                    </tr>
                </tbody>
            }
        }
    </table>
</div>
<script>
    function Deletar(id) {
        window.location.href = "../Cliente/DeletarCliente/" + id;
    }
    function Editar(id) {
        window.location.href = "../Cliente/CadastrarCliente/" + id;
    }
</script>